onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - unrs-resolver

auditConfig:
  minimumReleaseAge: 0

allowBuilds:
  '@prisma/engines': true
  prisma: true
  unrs-resolver: true
